file(GLOB TEST_SOURCES src/*.c)
message("First file: ${CMAKE_CURRENT_SOURCE_DIR}/src/utils.c")
list(REMOVE_ITEM TEST_SOURCES src/utils.c)
list(REMOVE_ITEM TEST_SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/utils.c)
foreach(src IN LISTS TEST_SOURCES)
  if(src MATCHES "utils.c")
    message("FOUND utils.c: ${src}")
  endif()
endforeach()
